---
name: Build Images for PRs
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'main'
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "hobbyfarm/hf-provisioner-digitalocean:${{ github.event.pull_request.head.sha }}"
      - name: Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEMETER_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'An image has been built, my little sprouts. Find it here: hobbyfarm/hf-provisioner-digitalocean:${{ github.event.pull_request.head.sha }}'
            })