---
name: Build Images for PRs
on:
  pull_request_target:
    types:
      - synchronize
    branches:
      - 'main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and store
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: "hobbyfarm/hf-provisioner-digitalocean:pr-${{ github.event.pull_request.head.sha }}"
          outputs: type=oci,dest=/image.tar
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: oci-image
          path: /image.tar
          retention-days: 1